### ISSUE TITLE
Switch logging to astropy

### ISSUE THREAD

**Issue by e-koch** [radio-astro-tools/signal-id#25]
Switch in `RadioMask`, add to  `Noise`.

**Comment by e-koch** [comment]
There's other issues with the current logging. This error appears while creating a ```RadioMask``` object:
```
Traceback (most recent call last):
  File "/Users/eric/anaconda/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/Users/eric/anaconda/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/Users/eric/anaconda/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/Users/eric/anaconda/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file mask.py, line 135
```

I'd rather switch the logging than fix this issue, for the time being.
